default_config:
logger:
  default: error
  logs:
    custom_components.wienerlinien: debug

debugpy:

sensor:
  - platform: wienerlinien
    stops: '911'
    firstnext: first
  - platform: wienerlinien
    stops: '923'
    firstnext: next
  - platform: wienerlinien
    firstnext: first
    stops:
      - '3835'
      - '3836'
